"""initial multi-tenant schema

Revision ID: 1a319f418af3
Revises: 
Create Date: 2026-06-30 21:08:39.837198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import fantasy.db.base  # custom GUID type used below

# revision identifiers, used by Alembic.
revision: str = '1a319f418af3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clerk_user_id'), ['clerk_user_id'], unique=True)

    op.create_table('chat_usage',
    sa.Column('user_id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day')
    )
    op.create_table('espn_credentials',
    sa.Column('user_id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('s2_enc', sa.Text(), nullable=False),
    sa.Column('swid_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('leagues',
    sa.Column('id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('user_id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('espn_league_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'espn_league_id', 'season', name='uq_league_user_espn_season')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_user_id'), ['user_id'], unique=False)

    op.create_table('proposals',
    sa.Column('id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('user_id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('league_id', fantasy.db.base.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_proposal_user_idempotency')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_user_id'), ['user_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('league_id', fantasy.db.base.GUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_league_id'), ['league_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_league_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_user_id'))
        batch_op.drop_index(batch_op.f('ix_proposals_league_id'))

    op.drop_table('proposals')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_user_id'))

    op.drop_table('leagues')
    op.drop_table('espn_credentials')
    op.drop_table('chat_usage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_clerk_user_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
