"""league rules overrides + draft plan

Revision ID: 6935d97e8d04
Revises: 6e34cf0afe6b
Create Date: 2026-07-06 22:06:14.425165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6935d97e8d04'
down_revision: Union[str, Sequence[str], None] = '6e34cf0afe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_detected', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
        # server_default backfills existing rows (NOT NULL add-column on Postgres
        # needs a default); dropped right after so new rows rely on the ORM default.
        batch_op.add_column(sa.Column('settings_overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('settings_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('draft_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('draft_plan_built_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('settings_overrides', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('draft_plan_built_at')
        batch_op.drop_column('draft_plan')
        batch_op.drop_column('settings_updated_at')
        batch_op.drop_column('settings_overrides')
        batch_op.drop_column('settings_detected')

    # ### end Alembic commands ###
